frappe.pages["arkan-help-onboarding"].on_page_load = async function(wrapper) {
    const page = frappe.ui.make_app_page({ parent: wrapper, title: __("Arkan Help Onboarding"), single_column: true });
    page.set_secondary_action(__("Skip"), () => frappe.set_route("app"));
    const $c = $(page.body).html('<div id="arkan_help_onboarding-container"></div>').find("#arkan_help_onboarding-container");
    const B = "#06B6D4", BL = "#CFFAFE";
    const steps = [
        { title: __("Welcome to Arkan Help"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><svg viewBox="0 0 120 120" width="120" height="120"><circle cx="60" cy="60" r="55" fill="${BL}" stroke="${B}" stroke-width="3"><animate attributeName="r" values="52;55;52" dur="3s" repeatCount="indefinite"/></circle><text x="60" y="68" text-anchor="middle" font-size="36" font-weight="bold">❓</text></svg><h3 style="color:${B};margin-top:16px">${__("Arkan Help")}</h3><p style="max-width:500px;margin:12px auto">${__("Contextual Help & Self-Documentation System")}</p></div>`; } },
        { title: __("File-Based Help"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">❓</span><h3 style="color:${B};margin-top:12px">${__("File-Based Help")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use File-Based Help in Arkan Help.")}</p></div>`; } },
        { title: __("Field Help Icons"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">❓</span><h3 style="color:${B};margin-top:12px">${__("Field Help Icons")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use Field Help Icons in Arkan Help.")}</p></div>`; } },
        { title: __("Navbar Help"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">❓</span><h3 style="color:${B};margin-top:12px">${__("Navbar Help")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use Navbar Help in Arkan Help.")}</p></div>`; } },
        { title: __("Role Guides"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">❓</span><h3 style="color:${B};margin-top:12px">${__("Role Guides")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use Role Guides in Arkan Help.")}</p></div>`; } },
        { title: __("6-Level Resolution"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">❓</span><h3 style="color:${B};margin-top:12px">${__("6-Level Resolution")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use 6-Level Resolution in Arkan Help.")}</p></div>`; } },
        { title: __("RTL Support"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">❓</span><h3 style="color:${B};margin-top:12px">${__("RTL Support")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use RTL Support in Arkan Help.")}</p></div>`; } },
        { title: __("Multi-Language"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">❓</span><h3 style="color:${B};margin-top:12px">${__("Multi-Language")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use Multi-Language in Arkan Help.")}</p></div>`; } },
        { title: __("You are Ready!"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:4em">🎉</span><h3 style="color:${B};margin-top:16px">${__("Onboarding Complete!")}</h3><p style="max-width:500px;margin:12px auto">${__("You are now ready to use Arkan Help. Use ❓ for help.")}</p><div style="margin-top:20px"><button class="btn btn-primary btn-lg" onclick="frappe.set_route('app')">${__("Go to Desk")}</button></div></div>`; } },
    ];
    if(frappe.visual&&frappe.visual.Storyboard) frappe.visual.Storyboard.create({container:$c[0],steps,brand_color:B,navigation:"both",showProgress:true});
    else { let h='<div style="max-width:800px;margin:0 auto;padding:20px">'; steps.forEach((s,i)=>{const d=document.createElement("div");if(s.content)s.content(d);h+=`<div style="margin-bottom:24px;padding:20px;border:1px solid var(--border-color);border-radius:12px"><h2 style="color:${B}">${s.title}</h2>${d.innerHTML||""}</div>`}); h+="</div>"; $c.html(h); }
};
